apiVersion: v1
kind: Service
metadata:
  name: neuroplex-coordinator-service
  namespace: neural-swarm
  labels:
    app.kubernetes.io/name: neuroplex
    app.kubernetes.io/component: coordinator
    app.kubernetes.io/part-of: neural-swarm-system
spec:
  selector:
    app.kubernetes.io/name: neuroplex
    app.kubernetes.io/component: coordinator
  ports:
  - name: coordinator
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: neuroplex-worker-service
  namespace: neural-swarm
  labels:
    app.kubernetes.io/name: neuroplex
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: neural-swarm-system
spec:
  selector:
    app.kubernetes.io/name: neuroplex
    app.kubernetes.io/component: worker
  ports:
  - name: worker
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: neuroplex-external-service
  namespace: neural-swarm
  labels:
    app.kubernetes.io/name: neuroplex
    app.kubernetes.io/component: external
    app.kubernetes.io/part-of: neural-swarm-system
spec:
  selector:
    app.kubernetes.io/name: neuroplex
    app.kubernetes.io/component: coordinator
  ports:
  - name: coordinator
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer